---
title: "2021 Spring Synthetic Biology Class Readings"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Readings

* Textbook - __Synthetic Biology - A Primer (Revised Edition)__ (2015) ICP ISBN:1783268794 
* [KU library Ebook](https://library.korea.ac.kr/datause/ebook/ebook-search-a/?fi1=&q1=synthetic%20biology%20a%20primer) or [Amazon](https://www.amazon.com/Synthetic-Biology-Revised-Geoff-Baldwin/dp/1783268794)

#### Week1
* (**_Homework_**) Foundations for engineering biology _Nature_ (2005) Nov 24;438(7067):449-53. doi: 10.1038/nature04342. [PMID:16306983](https://pubmed.ncbi.nlm.nih.gov/16306983/)

#### Week2
* A brief history of synthetic biology _Nat Rev Microbiol_ (2014) May;12(5):381-90. doi: 10.1038/nrmicro3239. [PMID:24686414](https://pubmed.ncbi.nlm.nih.gov/24686414/)

* (**_Homework_**) The second decade of synthetic biology: 2010-2020
_Nat Commun_ (2020) Oct 14;11(1):5174. doi: 10.1038/s41467-020-19092-2. [PMID:33057059](https://pubmed.ncbi.nlm.nih.gov/33057059/)


#### Week3
##### _DNA Reading_ - sequencing
1. DNA sequencing
* Maxam-Gilbert sequencing [wiki](https://en.wikipedia.org/wiki/Maxam%E2%80%93Gilbert_sequencing) -"A new method for sequencing DNA" _PNAS_ (1977) 74 (2): 560–4. doi: 10.1073/pnas.74.2.560. [PMID: 265521](https://pubmed.ncbi.nlm.nih.gov/265521)
* Sanger sequencing [wiki](https://en.wikipedia.org/wiki/Sanger_sequencing) - "A rapid method for determining sequences in DNA by primed synthesis with DNA polymerase" _J Mol Biol_ (1975) 94 (3): 441–8. doi: 10.1016/0022-2836(75)90213-2. [PMID: 1100841](https://pubmed.ncbi.nlm.nih.gov/1100841)

2. Next generation sequencing NGS
* Coming of age: ten years of next-generation sequencing technologies _Nat Rev Genet_ (2016) May 17;17(6):333-51. doi: 10.1038/nrg.2016.49. [PMID:27184599](https://pubmed.ncbi.nlm.nih.gov/27184599/)


#### Week4
##### _DNA Writing_ - synthesis

* (**_Review_**) Synthetic DNA Synthesis and Assembly: Putting the Synthetic in Synthetic Biology
_Cold Spring Harb Perspect Biol_ (2017) Jan 3;9(1):a023812. [PMID:28049645](https://pubmed.ncbi.nlm.nih.gov/28049645/)

1. Chemical synthesis - oligomer synthesis based on phosphoramidite chemistry [wiki](https://en.wikipedia.org/wiki/Oligonucleotide_synthesis)

2. Lager-scale synthesis - oligomer/gene synthesis
* Large-scale de novo DNA synthesis: technologies and applications _Nat Methods_ (2014) May;11(5):499-507. doi: 10.1038/nmeth.2918. [PMID:24781323](https://pubmed.ncbi.nlm.nih.gov/24781323/)

3. Biochemical synthesis
* The race for enzymatic DNA synthesis heats up _Nature_ (2019) Feb;566(7745):565. doi: 10.1038/d41586-019-00682-0. [PMID:30804572](https://pubmed.ncbi.nlm.nih.gov/30804572/)

#### Week5
##### _DNA Writing_ - assembly
4. Assembly - gene/genome synthesis

* Polymerase cycling assemlby (PCA) - "Single step assembly of a gene and entire plasmid from large numbers of oligodeoxyribonucleotides" _Gene_ (1995) 164 (1): 49–53. doi: 10.1016/0378-1119(95)00511-4. [PMID: 7590320](https://pubmed.ncbi.nlm.nih.gov/7590320)
* Ligation cyling reaction (LCR) - "Scaling up the ligase chain reaction-based approach to gene synthesis" _Biotechniques_ (2001) Feb;30(2):249-52. doi: 10.1007/978-1-4939-6343-0_8. [PMID: 27671935](https://pubmed.ncbi.nlm.nih.gov/27671935/)
* 3A-assembly [iGEM HQ](http://parts.igem.org/Assembly:3A_Assembly)
* iGEM standard assembly [iGEM standard](http://parts.igem.org/Help:Assembly)
* Gibson assembly [2010 iGEM Cambridge](http://2010.igem.org/Team:Cambridge/Gibson/Introduction), [NEB - a commercial kit](https://international.neb.com/applications/cloning-and-synthetic-biology/dna-assembly-and-cloning/gibson-assembly)
* Goldgen gate assembly [NEB - a commercial kit](https://international.neb.com/applications/cloning-and-synthetic-biology/dna-assembly-and-cloning/golden-gate-assembly)

#### Week6
* (**_Homework_**) A synthetic oscillatory network of transcriptional regulators _Nature_ (2000) Jan 20;403(6767):335-8. doi: 10.1038/35002125. [PMID:10659856](https://pubmed.ncbi.nlm.nih.gov/10659856/)

* (**_Homework_**) Creation of a bacterial cell controlled by a chemically synthesized genome _Science_ (2010) Jul 2;329(5987):52-6. doi: 10.1126/science.1190719. [PMID:20488990](https://pubmed.ncbi.nlm.nih.gov/20488990/)


#### Week7
##### Minimal cell and genome
* __The seven pillars of life__ _Science_ (2002) Mar 22;295(5563):2215-6. doi: 10.1126/science.1068489. [PMID: 11910092](https://pubmed.ncbi.nlm.nih.gov/11910092/)
* __Minimal Cells-Real and Imagined__ _Cold Spring Harb Perspect Biol_ (2017 Dec) 1;9(12):a023861. doi: 10.1101/cshperspect.a023861. [PMID: 28348033](https://pubmed.ncbi.nlm.nih.gov/28348033/)

##### JCVI Synthetic Genomes
* __Genome transplantation__ - "Genome transplantation in bacteria: changing one species to another" _Science_ (2007) Aug 3;317(5838):632-8. doi: 10.1126/science.1144622. [PMID: 17600181](https://pubmed.ncbi.nlm.nih.gov/17600181/)
* _Mycoplasma genitalium_ __Synthetic genome__ - "Complete chemical synthesis, assembly, and cloning of a Mycoplasma genitalium genome" _Science_ (2008) Feb 29;319(5867):1215-20. doi: 10.1126/science.1151721. [PMID: 18218864](https://pubmed.ncbi.nlm.nih.gov/18218864/)
* __JCVI Syn1.0__ - "Creation of a bacterial cell controlled by a chemically synthesized genome" _Science_ (2010) Jul 2;329(5987):52-6. doi: 10.1126/science.1190719. [PMID: 20488990](https://pubmed.ncbi.nlm.nih.gov/20488990/)
* __JCVI Syn3.0__ - "Design and synthesis of a minimal bacterial genome" _Science_ (2016) Mar 25;351(6280):aad6253. doi: 10.1126/science.aad6253.
[PMID: 27013737](https://pubmed.ncbi.nlm.nih.gov/27013737/)
* Book to read - "Life at the speed of light" by Craig Ventor [(amazon)](https://www.amazon.com/Life-Speed-Light-Double-Digital-ebook/dp/B00C1N5WRK), "인공생명의 탄생" [(Korean translation - library)](https://library.korea.ac.kr/main-search-result/?q=%EC%9D%B8%EA%B3%B5%EC%83%9D%EB%AA%85%EC%9D%98+%ED%83%84%EC%83%9D+%3A+%ED%95%A9%EC%84%B1%EC%83%9D%EB%AC%BC%ED%95%99%EC%9D%80+%EC%96%B4%EB%96%BB%EA%B2%8C+%EC%9D%B8%EA%B3%B5%EC%83%9D%EB%AA%85%EC%9D%84+%EB%A7%8C%EB%93%A4%EC%97%88%EB%8A%94%EA%B0%80)

##### Synthetic yeast
* Sc2.0 [Sc2.0 project](http://syntheticyeast.org/sc2-0/)
* __SCRaMbLE__ - "The Saccharomyces cerevisiae SCRaMbLE system and genome minimization" _Bioeng Bugs_ (2012) 3(3):168-71. doi: 10.4161/bbug.19543. [PMID: 22572789](https://pubmed.ncbi.nlm.nih.gov/22572789/)

